version: "3.9"

services:
  documents:
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - documents.wsgi:application
      - --bind
      - 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    volumes:
      - ./documents/docs_base:/documents/docs_base
