# Generated by Django 5.1.1 on 2024-10-03 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Brand')),
                ('slug', models.SlugField(max_length=100, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(db_index=True, max_length=50, verbose_name='Mode')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('slave_id', models.IntegerField(verbose_name='Slave ID')),
                ('speed', models.CharField(choices=[(None, 'speed')], default='9600', max_length=6, verbose_name='Speed')),
                ('paritet', models.CharField(choices=[(None, 'paritet'), ('E', 'Even'), ('N', 'None'), ('O', 'Odd')], default='N', max_length=1, verbose_name='Paritet')),
                ('bit', models.CharField(choices=[(None, 'bits')], default='8', max_length=1, verbose_name='Bits')),
                ('stop_bit', models.CharField(choices=[(None, 'storp bits')], default='1', max_length=1, verbose_name='Stop bit')),
                ('ip_address', models.CharField(max_length=15, verbose_name='IP address')),
                ('mask', models.CharField(max_length=15, verbose_name='Mask')),
                ('gateway', models.CharField(max_length=15, verbose_name='Gateway')),
                ('description', models.TextField(blank=True, default=' ', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'setting',
                'verbose_name_plural': 'settings',
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Device')),
                ('slug', models.SlugField(max_length=150, verbose_name='URL')),
                ('description', models.TextField(blank=True, default=' ', verbose_name='Description')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='instruction.brand', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='Name')),
                ('slug', models.SlugField(max_length=120, verbose_name='URL')),
                ('description', models.TextField(blank=True, default=' ', verbose_name='Description')),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices_files', to='instruction.device', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='InstructionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='Name')),
                ('slug', models.SlugField(max_length=120, verbose_name='URL')),
                ('description', models.TextField(blank=True, default=' ', verbose_name='Description')),
                ('device_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devices_instructs', to='instruction.device', verbose_name='Instruction')),
            ],
            options={
                'verbose_name': 'instruction',
                'verbose_name_plural': 'instructions',
                'db_table': 'instructions',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='Name')),
                ('slug', models.SlugField(max_length=120, verbose_name='URL')),
                ('description', models.TextField(blank=True, default=' ', verbose_name='Description')),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices_networks', to='instruction.device', verbose_name='Netork')),
                ('settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instruction.settings', verbose_name='Settings')),
            ],
            options={
                'verbose_name': 'network',
                'verbose_name_plural': 'networks',
                'db_table': 'networks',
            },
        ),
    ]
