# Generated by Django 5.1.1 on 2024-10-04 04:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruction", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="device_id",
            new_name="network_id",
        ),
        migrations.AddField(
            model_name="file",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="file",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Date updated"),
        ),
        migrations.AddField(
            model_name="settings",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Date updated"),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crm_id",
                    models.CharField(
                        db_index=True, max_length=10, verbose_name="ID CRM"
                    ),
                ),
                ("company", models.CharField(max_length=120, verbose_name="Company")),
                ("prject", models.CharField(max_length=120, verbose_name="Project")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="URL"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Date updated"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default=" ", verbose_name="Info"),
                ),
                (
                    "device_id",
                    models.ManyToManyField(
                        to="instruction.device", verbose_name="Device"
                    ),
                ),
            ],
            options={
                "verbose_name": "project",
                "verbose_name_plural": "projects",
                "db_table": "project",
            },
        ),
    ]
