# Generated by Django 5.1.1 on 2024-10-04 06:13

import instruction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "instruction",
            "0004_instructionfile_created_at_instructionfile_docs_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="description",
        ),
        migrations.AddField(
            model_name="file",
            name="file_configs",
            field=models.FileField(
                blank=True,
                upload_to=instruction.models.path_to_file_configs,
                verbose_name="Photo config",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="file_report",
            field=models.FileField(
                blank=True,
                upload_to=instruction.models.path_to_file_report,
                verbose_name="Photo report",
            ),
        ),
    ]
