# Generated by Django 5.1.1 on 2024-10-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruction", "0006_remove_file_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="designation",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Обозначение"  # type: ignore
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(db_index=True, max_length=80, verbose_name="Device"),
        ),
    ]
