# Generated by Django 5.1.1 on 2024-10-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruction", "0008_wavesensor"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="serial_num",
            field=models.CharField(
                default=1, max_length=15, verbose_name="Serial number"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="device",
            name="termodate",
            field=models.BooleanField(default=False, verbose_name="Termo date"),
        ),
        migrations.AlterField(
            model_name="wavesensor",
            name="temp_error",
            field=models.CharField(
                default="90", max_length=3, verbose_name="Temperature over"
            ),
        ),
        migrations.AlterField(
            model_name="wavesensor",
            name="temp_warning",
            field=models.CharField(
                default="85", max_length=3, verbose_name="Temperature warning"
            ),
        ),
    ]
