# Generated by Django 5.1.1 on 2024-10-07 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruction", "0009_device_serial_num_device_termodate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="device_id",
        ),
        migrations.AddField(
            model_name="project",
            name="device_id",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="instruction.device",
                verbose_name="Device",
            ),
            preserve_default=False,
        ),
    ]
