# Generated by Django 5.1.1 on 2024-10-17 03:46

import imagekit.models.fields
import instruction.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0013_instructionfile_brand_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='icon',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=instruction.models.path_to_icon_brand, verbose_name='Logo'),
        ),
    ]
