# Generated by Django 5.1.1 on 2024-10-30 09:34

import django.db.models.deletion
import instruction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0019_alter_device_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=110, verbose_name='Название')),
                ('file', models.FileField(blank=True, upload_to=instruction.models.path_to_file, verbose_name='Файл')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='instruction.project', verbose_name='Проект')),
            ],
        ),
    ]
