# Generated by Django 5.1.1 on 2024-10-31 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instruction", "0020_fileproject"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fileproject",
            options={"verbose_name": "file", "verbose_name_plural": "files"},
        ),
        migrations.AlterModelTable(
            name="fileproject",
            table="file_project",
        ),
    ]
