# Generated by Django 5.1.1 on 2024-12-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruction", "0023_alter_filedevice_file_configs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="archive",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Archive"
            ),
        ),
    ]
