# Generated by Django 5.1.1 on 2025-02-24 06:57

import imagekit.models.fields
import instruction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruction", "0024_alter_project_archive"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileproject",
            name="file_photos",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                upload_to=instruction.models.path_to_file_report,  # type: ignore
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="filedevice",
            name="file_configs",
            field=models.FileField(
                blank=True,
                upload_to=instruction.models.path_to_file_configs,
                verbose_name="Файлы",
            ),
        ),
    ]
