# Generated by Django 5.1.1 on 2025-02-24 08:26

import instruction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruction", "0025_fileproject_file_photos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileproject",
            name="file_photos",
            field=models.ImageField(
                blank=True,
                upload_to=instruction.models.path_to_file_report,  # type: ignore
                verbose_name="Photo",
            ),
        ),
    ]
